import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import UserContextProvider from "@/context/userContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <UserContextProvider>
        <body >
          {children}
          <Toaster />
        </body>
      </UserContextProvider>
    </html>
  );
}
